name: Tuya Energy Logger

on:
  schedule:
    - cron: '*/30 * * * *' # Se ejecuta cada 30 minutos
  workflow_dispatch: # Permite probarlo a mano cuando quieras

permissions:
  contents: write

jobs:
  run-logger:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de captura
        env:
          API_ID: ${{ secrets.API_ID }}
          API_SECRET: ${{ secrets.API_SECRET }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
        run: python logger.py

      - name: Guardar cambios en el CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Actualización automática del historial energético'
          file_pattern: 'historico_energia.csv'
